In [2]:
import pandas as pd

In [12]:
data=pd.read_excel('../../data/sample.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: '../../data/sample.xlsx'

In [10]:
data.head()

,StoreId,Date,CheckTime,UniqueCheckId,PLU,MenuItemId,MenuItemName,ItemCount,Amount,Tax,LineType,LineTypeDescription,CategoryName,ReductionId,ReductionName,order_channel,Order_type,discount_amt,DiscountName
0,1052,2023-02-08,12:34:00,3923010523082,47584,68,Add Lettuce,1,0.00,0.00,1,Sale,Condiments,0,NaN,Drive-Thru\n,Drive,NaN,NaN
1,1052,2023-02-08,12:34:00,3923010523082,49020,212,Medium Potato Oles,1,2.99,0.21,1,Sale,Potato OlÃ©s,0,NaN,Drive-Thru\n,Drive,NaN,NaN
2,1052,2023-02-08,12:34:00,3923010523082,50198,6,The Boss Bowl - Grilled Chicken,1,6.69,0.48,1,Sale,Boss,0,NaN,Drive-Thru\n,Drive,NaN,NaN
3,1052,2023-02-08,12:34:00,3923010523082,49107,71,Pico de Gallo,1,0.00,0.00,1,Sale,Condiments,0,NaN,Drive-Thru\n,Drive,NaN,NaN
4,1052,2023-02-08,12:34:00,3923010523082,51844,1179,More Ingredients,1,0.00,0.00,1,Sale,Condiments,0,NaN,Drive-Thru\n,Drive,NaN,NaN