In [2]:
import pandas as pd

In [21]:
store=pd.read_csv('../output_files/weekly_summary_sheet2.csv')
weekly_summary=pd.read_csv('../output_files/weekly_store.csv')

# highlight 1 : store id 03222-00033 dropes by 50% weekly revenue 

Store ID 03222-00033 – WoW Drop Analysis
• Initial WoW drop: -50%
• Issue found: Missing current week's Friday data
• Adjustment: Used last Friday's sales as proxy
• Adjusted WoW drop: -33%
• Note: Still highest drop among 72 stores

In [42]:
least_wow_change_store=store.sort_values(by='WoW Change').head(1)
least_wow_change_store

,Week,Brand,Store Id,Total Revenue,Total Orders,Average Order Value,WoW Change,Top2MenuItems,TopOrderMethod
14,2025-06-08,Little Caesars,03222-00033,5536.1,250,22.14,-50.2,"EMB Pepperoni, Classic Pepperoni",Mobile

In [43]:
weekly_summary[weekly_summary['FranchiseStore'].isin(least_wow_change_store['Store Id'])].sort_values(by='BusinessDate').head(3)

,FranchiseStore,BusinessDate,NetAmount,OrderId,Average Order Value,WoW Change,Brand,Top2MenuItems,TopOrderMethod
9,03222-00033,2025-06-01,11122.47,484,22.98,NaN,Little Caesars,"Classic Pepperoni, EMB Pepperoni",Mobile
86,03222-00033,2025-06-08,5536.12,250,22.14,-50.2,Little Caesars,"EMB Pepperoni, Classic Pepperoni",Mobile

In [50]:
# checked the data for one of the stores
# missing friday
data = pd.read_csv(
    "/Users/nooreen/Desktop/High_margin/VIBE/e-commerce_report/weekly_sales/transactional data/june_11.csv",
    parse_dates=["BusinessDate"],

)
# data=data[data.index> "2025-05-25 00:00:00"]
store_id_33=data[(data['FranchiseStore']=='03222-00033')]

store_id_33

,FranchiseStore,BusinessDate,DateTimePlaced,NetAmount,Quantity,OrderId,ItemId,MenuItemName,BundleName,OrderPlacedMethod
7119,03222-00033,2025-05-26,5/26/2025 12:00,0.00,0,1057319,-,NaN,4 Cheese Crazy Puffs® Crave Combo with a 16oz ...,Website
7120,03222-00033,2025-05-26,5/26/2025 12:01,0.00,0,1057320,-,NaN,Crazy Combo,DoorDash
7121,03222-00033,2025-05-26,5/26/2025 12:37,0.00,0,1057330,-,NaN,Online 2 Dippers,Mobile
7122,03222-00033,2025-05-26,5/26/2025 12:37,0.00,0,1057330,-,NaN,Deep!Deep! Dish Lunch Combo Online,Mobile
7123,03222-00033,2025-05-26,5/26/2025 13:05,0.00,0,1057340,-,NaN,4 Cheese Crazy Puffs® Crave Combo with a 16oz ...,Mobile
...,...,...,...,...,...,...,...,...,...,...
289610,03222-00033,2025-05-25,5/25/2025 20:56,0.00,0,1057306,6,Tip,NaN,Mobile
289797,03222-00033,2025-05-25,5/25/2025 17:27,11.69,1,1057219,201004,Ultimate Supreme,NaN,Website
289928,03222-00033,2025-05-25,5/25/2025 14:03,12.99,1,1057139,201004,Ultimate Supreme,NaN,Mobile
289929,03222-00033,2025-05-25,5/25/2025 16:38,12.99,1,1057201,201004,Ultimate Supreme,NaN,Mobile
290037,03222-00033,2025-05-25,5/25/2025 18:36,15.67,1,1057250,201004,Ultimate Supreme,NaN,DoorDash

In [51]:
# check fordailyt sale to estimaare for friday sale
store_id_33.groupby('BusinessDate').agg({'NetAmount':'sum'}).sort_index().head(10)

              NetAmount
BusinessDate
2025-05-25      1605.97
2025-05-26       985.45
2025-05-27      1092.40
2025-05-28      1377.79
2025-05-29      1437.54
2025-05-30      1827.29
2025-05-31      2913.82
2025-06-01      1488.18
2025-06-02       783.44
2025-06-03      1060.30

In [53]:
# last friday it did 1827.29
# asuming same
5536.12+1827.29
(7363.41-11122.47	)/11122.47*100

-33.796989337799964

# highlight 2

In [13]:
top_wow_change_store=store.sort_values(by='WoW Change',ascending=False).head(2)
top_wow_change_store

,Week,Brand,Store Id,Total Revenue,Total Orders,Average Order Value,WoW Change,Top2MenuItems,TopOrderMethod
20,2025-06-08,Little Caesars,03222-00032,12459.9,552,22.57,29.4,"EMB Pepperoni, Classic Pepperoni",Mobile
47,2025-06-08,Little Caesars,01940-00009,12714.5,605,21.02,15.7,"EMB Pepperoni, Classic Pepperoni",Mobile

In [16]:
top_AOA_store=store.sort_values(by='Average Order Value',ascending=False).head(3)
top_AOA_store

,Week,Brand,Store Id,Total Revenue,Total Orders,Average Order Value,WoW Change,Top2MenuItems,TopOrderMethod
8,2025-06-08,Little Caesars,03222-00028,7709.7,291,26.49,1.6,"EMB Pepperoni, Classic Pepperoni",Website
49,2025-06-08,Little Caesars,03222-00017,17215.2,727,23.68,-3.7,"EMB Pepperoni, Classic Pepperoni",Mobile
27,2025-06-08,Little Caesars,01826-00003,9376.2,401,23.38,-1.7,"EMB Pepperoni, Classic Pepperoni",Mobile

In [17]:
least_AOA_store=store.sort_values(by='Average Order Value').head(3)
least_AOA_store

,Week,Brand,Store Id,Total Revenue,Total Orders,Average Order Value,WoW Change,Top2MenuItems,TopOrderMethod
45,2025-06-08,Little Caesars,01389-00013,9160.3,497,18.43,-11.1,"EMB Pepperoni, Classic Pepperoni",Mobile
15,2025-06-08,Little Caesars,03222-00046,10154.7,545,18.63,-7.7,"Classic Pepperoni, EMB Pepperoni",Mobile
12,2025-06-08,Little Caesars,03222-00047,6592.6,351,18.78,-22.8,"Classic Pepperoni, EMB Pepperoni",Mobile

In [54]:
store['Average Order Value'].describe()

count    72.000000
mean     21.454028
std       1.302815
min      18.430000
25%      20.695000
50%      21.545000
75%      22.190000
max      26.490000
Name: Average Order Value, dtype: float64

# highlight 3

In [58]:
store=pd.read_csv('../output_files/weekly_summary_sheet2.csv')
weekly_summary=pd.read_csv('../output_files/weekly_store.csv')
store.head(3)

,Week,Brand,Store Id,Total Revenue,Total Orders,Average Order Value,WoW Change,Top2MenuItems,TopOrderMethod
0,2025-06-08,Little Caesars,03222-00038,20168.2,1010,19.97,4.4,"EMB Pepperoni, Classic Pepperoni",Mobile
1,2025-06-08,Little Caesars,03646-00001,9810.2,446,22.00,-10.8,"Classic Pepperoni, Crazy Bread",Mobile
2,2025-06-08,Little Caesars,03222-00022,6405.1,278,23.04,0.1,"Classic Pepperoni, EMB Pepperoni",Mobile

In [64]:
store['TopOrderMethod'].value_counts().head(10)

TopOrderMethod
Mobile     71
Website     1
Name: count, dtype: int64

In [65]:
store[store['TopOrderMethod']=='Website'].sort_values(by='WoW Change',ascending=False).head(3)

,Week,Brand,Store Id,Total Revenue,Total Orders,Average Order Value,WoW Change,Top2MenuItems,TopOrderMethod
8,2025-06-08,Little Caesars,03222-00028,7709.7,291,26.49,1.6,"EMB Pepperoni, Classic Pepperoni",Website

# highlights 4

In [68]:
channel=pd.read_csv('../output_files/weekly_summary_sheet3.csv')
channel.head(2)

,Week,Brand,Store Id,Digital Channel,Total Revenue,Total Orders,Average Order Value,WoW Change,Top2MenuItems
0,2025-06-08,Little Caesars,03222-00036,DoorDash,3370.5,176,19.15,-15.9,"EMB Pepperoni, Custom Stuffed Crust"
1,2025-06-08,Little Caesars,01978-00005,Website,3713.2,148,25.09,46.3,"Classic Cheese, Classic Pepperoni"

In [73]:
channel.groupby(['Digital Channel','Top2MenuItems']).agg({'Total Revenue':'sum'}).sort_values(by='Total Revenue',ascending=False).head(10)

                                                                Total Revenue
Digital Channel Top2MenuItems
Mobile          Classic Pepperoni, Classic Cheese                    131428.4
                Classic Pepperoni, EMB Pepperoni                      97301.3
Website         Classic Pepperoni, Classic Cheese                     79636.4
Mobile          Classic Pepperoni, Crazy Bread                        64947.1
Website         Classic Pepperoni, EMB Pepperoni                      46801.6
DoorDash        EMB Pepperoni, EMB Cheese                             44906.9
                EMB Pepperoni, Custom Stuffed Crust                   29744.6
                EMB Pepperoni, Stuffed Crazy Crust Pepperoni          28341.2
Mobile          Classic Pepperoni, Stuffed Crust EMB Pepperoni        27977.7
UberEats        EMB Pepperoni, Caesar Wings                           18406.7

In [77]:
aux=channel.groupby('Digital Channel').agg({'Total Revenue':'sum'}).sort_values(by='Total Revenue',ascending=False).reset_index()

In [79]:
aux['pct']=aux['Total Revenue']/aux['Total Revenue'].sum()*100
aux

  Digital Channel  Total Revenue        pct
0          Mobile       390866.9  48.698473
1         Website       206479.2  25.725437
2        DoorDash       149869.3  18.672356
3        UberEats        51496.4   6.415985
4         Grubhub         3914.8   0.487749

In [95]:
least_wow_change_store=channel.sort_values(by='WoW Change').head(20)
least_wow_change_store.sort_values(by=['Store Id','Digital Channel','WoW Change'])

,Week,Brand,Store Id,Digital Channel,Total Revenue,Total Orders,Average Order Value,WoW Change,Top2MenuItems
133,2025-06-08,Little Caesars,01389-00004,UberEats,49.8,3,16.61,-76.3,"EMB Pepperoni, Crazy Bread"
10,2025-06-08,Little Caesars,01389-00010,UberEats,126.6,8,15.82,-61.8,"EMB Pepperoni, EMB Cheese"
55,2025-06-08,Little Caesars,01389-00011,Grubhub,24.8,2,12.42,-61.5,"Stuffed Crazy Crust Cheese, EMB Pepperoni"
277,2025-06-08,Little Caesars,01389-00014,UberEats,85.1,5,17.03,-46.3,"EMB Pepperoni, Crazy Bread"
154,2025-06-08,Little Caesars,01940-00021,Grubhub,65.4,3,21.80,-67.7,"Custom Round, EMB Pepperoni"
3,2025-06-08,Little Caesars,01944-00001,UberEats,45.4,3,15.15,-57.7,"Ultimate Supreme, EMB Pepperoni"
318,2025-06-08,Little Caesars,01944-00005,UberEats,126.1,5,25.22,-55.3,"EMB Pepperoni, 5 Meat Feast"
236,2025-06-08,Little Caesars,03222-00003,Grubhub,18.5,1,18.50,-61.7,Custom Stuffed Crust
226,2025-06-08,Little Caesars,03222-00004,Grubhub,19.1,1,19.10,-72.4,"SNS Bacon with Crazy Sauce, EMB Sausage"
285,2025-06-08,Little Caesars,03222-00017,UberEats,88.4,4,22.11,-57.9,"EMB Pepperoni, Custom Stuffed Crust"
259,2025-06-08,Little Caesars,03222-00022,Grubhub,11.9,1,11.94,-73.3,Stuffed Pretzel Crust with Pizza Sauce & Peppe...
258,2025-06-08,Little Caesars,03222-00024,UberEats,104.1,7,14.87,-56.0,"EMB Pepperoni, EMB Sausage"
49,2025-06-08,Little Caesars,03222-00028,Mobile,339.3,15,22.62,-45.6,"Classic Pepperoni, Thin Crust EMB Pepperoni"
67,2025-06-08,Little Caesars,03222-00033,DoorDash,1207.4,53,22.78,-41.8,"EMB Pepperoni, EMB Cheese"
64,2025-06-08,Little Caesars,03222-00033,Mobile,2231.0,112,19.92,-51.6,"Classic Pepperoni, Classic Cheese"
60,2025-06-08,Little Caesars,03222-00033,Website,1553.2,59,26.33,-56.9,"Classic Pepperoni, Classic Cheese"
13,2025-06-08,Little Caesars,03222-00039,Grubhub,14.1,1,14.08,-60.1,"EMB Pepperoni, Crazy Bread"
118,2025-06-08,Little Caesars,03222-00044,Grubhub,25.7,2,12.84,-73.7,"3 Meat Treat, EMB Sausage"
111,2025-06-08,Little Caesars,03646-00002,UberEats,251.0,16,15.69,-62.7,"EMB Pepperoni, Custom Stuffed Crust"
106,2025-06-08,Little Caesars,03646-00003,Grubhub,89.8,5,17.96,-45.2,"Custom Stuffed Crust, Ultimate Supreme"

In [96]:
least_wow_change_store['Store Id'].value_counts()

Store Id
03222-00033    3
01389-00004    1
03222-00044    1
03222-00028    1
01389-00014    1
01944-00005    1
03222-00024    1
01944-00001    1
03222-00017    1
03222-00039    1
01389-00011    1
03222-00003    1
01389-00010    1
03646-00002    1
01940-00021    1
03222-00004    1
03222-00022    1
03646-00003    1
Name: count, dtype: int64

In [103]:

least_wow_change_store[least_wow_change_store['Store Id']=='03222-00033']

,Week,Brand,Store Id,Digital Channel,Total Revenue,Total Orders,Average Order Value,WoW Change,Top2MenuItems
60,2025-06-08,Little Caesars,03222-00033,Website,1553.2,59,26.33,-56.9,"Classic Pepperoni, Classic Cheese"
64,2025-06-08,Little Caesars,03222-00033,Mobile,2231.0,112,19.92,-51.6,"Classic Pepperoni, Classic Cheese"
67,2025-06-08,Little Caesars,03222-00033,DoorDash,1207.4,53,22.78,-41.8,"EMB Pepperoni, EMB Cheese"

In [ ]:
# store id 03222-00033' appeared to the least wow change store in the channel data threshold <-40%
 this store apeaed to have a very low revenue in the channel data for three time with 3 different channels, website, , mobile doordash 
 with -56, -51 and -41 respectively

In [101]:
data[data['FranchiseStore']=='03222-00033']['OrderPlacedMethod'].value_counts()

OrderPlacedMethod
Mobile      1370
Website      836
DoorDash     452
UberEats     231
Grubhub       12
Name: count, dtype: int64

In [102]:
#top lowews wow
channel[channel['Store Id']=='01389-00004']

,Week,Brand,Store Id,Digital Channel,Total Revenue,Total Orders,Average Order Value,WoW Change,Top2MenuItems
119,2025-06-08,Little Caesars,01389-00004,Website,3471.0,128,27.12,29.1,"Classic Pepperoni, Classic Cheese"
133,2025-06-08,Little Caesars,01389-00004,UberEats,49.8,3,16.61,-76.3,"EMB Pepperoni, Crazy Bread"
150,2025-06-08,Little Caesars,01389-00004,DoorDash,2660.5,125,21.28,16.3,"EMB Pepperoni, EMB Cheese"
153,2025-06-08,Little Caesars,01389-00004,Mobile,5710.4,267,21.39,8.1,"Classic Pepperoni, Classic Cheese"

In [105]:
top_wow_change_store=channel.sort_values(by='WoW Change',ascending=False).head(20)
top_wow_change_store
# top_wow_change_store.sort_values(by=['Store Id','Digital Channel','WoW Change'])

,Week,Brand,Store Id,Digital Channel,Total Revenue,Total Orders,Average Order Value,WoW Change,Top2MenuItems
196,2025-06-08,Little Caesars,03222-00006,Grubhub,142.0,5,28.41,260.7,"Ultimate Supreme, EMB Pepperoni"
203,2025-06-08,Little Caesars,03222-00002,Grubhub,120.9,4,30.22,257.9,"Custom Round, Crazy Bread"
91,2025-06-08,Little Caesars,03646-00002,Grubhub,178.6,10,17.86,243.4,"EMB Pepperoni, Custom Detroit-Style Deep Dish"
297,2025-06-08,Little Caesars,01494-00005,UberEats,86.8,4,21.69,233.0,"Custom Stuffed Crust, 3 Meat Treat"
141,2025-06-08,Little Caesars,03222-00046,Grubhub,142.0,6,23.66,193.0,"Custom Stuffed Crust, Ultimate Supreme"
135,2025-06-08,Little Caesars,03222-00044,UberEats,185.2,10,18.52,187.8,"EMB Pepperoni, Custom Stuffed Crust"
182,2025-06-08,Little Caesars,03222-00010,UberEats,70.0,3,23.32,168.2,"Stuffed Crazy Crust Custom, Stuffed Crazy Crus..."
292,2025-06-08,Little Caesars,03222-00016,UberEats,257.5,14,18.39,159.4,"EMB Pepperoni, Caesar Wings"
20,2025-06-08,Little Caesars,03222-00036,Grubhub,122.5,5,24.49,155.3,"Caesar Wings, EMB Pepperoni"
29,2025-06-08,Little Caesars,01389-00008,UberEats,112.6,6,18.76,141.2,"EMB Pepperoni, 3 Meat Treat"
197,2025-06-08,Little Caesars,01826-00003,UberEats,73.1,6,12.19,132.5,"EMB Pepperoni, Pretzel Crust with Cheese Sauce..."
262,2025-06-08,Little Caesars,01389-00013,UberEats,446.2,29,15.39,112.0,"EMB Pepperoni, Crazy Bread"
163,2025-06-08,Little Caesars,01978-00002,Grubhub,297.1,12,24.76,108.7,"Caesar Wings, Stuffed Crazy Crust Cheese"
271,2025-06-08,Little Caesars,01944-00004,Grubhub,29.8,1,29.84,100.1,"3 Meat Treat, Italian Cheese Bread"
181,2025-06-08,Little Caesars,01944-00006,UberEats,154.0,8,19.25,98.4,"EMB Pepperoni, Hula Hawaiian H"
232,2025-06-08,Little Caesars,03222-00003,UberEats,314.5,14,22.46,94.9,"EMB Pepperoni, Crazy Bread"
4,2025-06-08,Little Caesars,03222-00035,UberEats,551.4,28,19.69,86.3,"EMB Pepperoni, Crazy Bread"
127,2025-06-08,Little Caesars,03222-00043,Grubhub,122.0,5,24.39,79.0,"Slices-N-Stix with Crazy Sauce, 3 Meat Treat"
130,2025-06-08,Little Caesars,01389-00005,UberEats,184.2,9,20.47,78.9,"EMB Pepperoni, Custom Stuffed Crust"
254,2025-06-08,Little Caesars,01494-00001,UberEats,664.6,36,18.46,73.7,"EMB Pepperoni, 5 Meat Feast"

In [109]:
channel.columns

Index(['FranchiseStore', 'OrderPlacedMethod', 'BusinessDate', 'NetAmount',
       'OrderId', 'Average Order Value', 'WoW Change', 'Top2MenuItems'],
      dtype='object')

In [112]:
channel=pd.read_csv('../output_files/weekly_channel.csv')
channel[channel['FranchiseStore']=='03222-00006'].sort_values(by=['OrderPlacedMethod','BusinessDate'])

,FranchiseStore,OrderPlacedMethod,BusinessDate,NetAmount,OrderId,Average Order Value,WoW Change,Top2MenuItems
15,03222-00006,DoorDash,2025-06-01,1846.29,86,21.47,NaN,"EMB Pepperoni, EMB Cheese"
523,03222-00006,DoorDash,2025-06-08,2107.62,96,21.95,14.2,"EMB Pepperoni, EMB Cheese"
14,03222-00006,Grubhub,2025-06-01,39.38,2,19.69,NaN,"EMB Cheese, Stuffed Pretzel Crust with Pizza S..."
521,03222-00006,Grubhub,2025-06-08,142.03,5,28.41,260.7,"Ultimate Supreme, EMB Pepperoni"
13,03222-00006,Mobile,2025-06-01,6965.83,353,19.73,NaN,"Classic Pepperoni, Crazy Bread"
498,03222-00006,Mobile,2025-06-08,7273.38,335,21.71,4.4,"Classic Pepperoni, Crazy Bread"
12,03222-00006,UberEats,2025-06-01,221.84,9,24.65,NaN,"Custom Round, Old World Fanceroni Pepperoni™"
496,03222-00006,UberEats,2025-06-08,181.97,12,15.16,-18.0,"EMB Pepperoni, Crazy Bread"
11,03222-00006,Website,2025-06-01,3027.40,134,22.59,NaN,"Classic Pepperoni, Classic Cheese"
494,03222-00006,Website,2025-06-08,2749.17,133,20.67,-9.2,"Classic Pepperoni, Classic Cheese"

In [114]:
(142-39)/39*100

264.1025641025641